name: Deploy React App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up SSH Key
    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DIGITALOCEAN_IP_ADDRESS }} >> ~/.ssh/known_hosts

    # React App Deployment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0' # Ensure this is the version you need

    - name: Install React App Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to DigitalOcean
      run: |
        ssh -tt -o StrictHostKeyChecking=no ${{ secrets.DIGITALOCEAN_SSH_USER }}@${{ secrets.DIGITALOCEAN_IP_ADDRESS }} << EOF
          cd /path/to/your/react/app/directory # Update this path to the actual path on your server
          git pull origin main
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm run build
          pm2 restart your-react-app-process || true # Update this with your actual pm2 process name
        EOF
      env:
        DIGITALOCEAN_SSH_USER: ${{ secrets.DIGITALOCEAN_SSH_USER }}
        DIGITALOCEAN_IP_ADDRESS: ${{ secrets.DIGITALOCEAN_IP_ADDRESS }}
